export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Info Section 1',
    headline: 'Section One Headline',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    buttonLabel: 'Back To Top',
    imgStart: false,
    img: require('../../images/svg-2.svg').default,
    alt: 'Rocket',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Info Section 2',
    headline: 'Section Two Headline',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    buttonLabel: 'Back To Top',
    imgStart: true,
    img: require('../../images/svg-3.svg').default,
    alt: 'Planet',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Info Section 3',
    headline: 'Section Three Headline',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    buttonLabel: 'Back To Top',
    imgStart: false,
    img: require('../../images/svg-4.svg').default,
    alt: 'Alien',
    dark: false,
    primary: false,
    darkText: true,
};